default:
  keepAliveMetrics:
    read:
      clientData:
        throttleIntervalInMs: 1000
      pagination:
        count: 5
    maxHitsPerHour: 60 # One hit per minute
    health:
      checkIntervalInMs: 30000
  db:
    mongo:
      address: localhost
      port: 27001
      databaseName: metrics